# Maps each of the 56 category CSV files (from quiz_dataset_56_categories.zip)
# to its display name and an icon (emoji) used on the Quizzes page.
# Order here = display order on the Quizzes page (matches the spec's category list).

CATEGORIES = [
    ("History", "History", "🏛️"),
    ("Math", "Math", "🧮"),
    ("Science", "Science", "🧪"),
    ("Space", "Space (Astronomy)", "🪐"),
    ("Kannada", "Kannada", "🗣️"),
    ("English", "English", "🔤"),
    ("Social_Science", "Social Science", "👥"),
    ("Software", "Software", "💻"),
    ("Hardware", "Hardware", "🖥️"),
    ("AI", "Artificial Intelligence (AI)", "🧠"),
    ("ML", "Machine Learning (ML)", "🤖"),
    ("GK", "General Knowledge (GK)", "💡"),
    ("Aptitude", "Aptitude", "🎯"),
    ("Web_Development", "Web Development", "🌐"),
    ("Puzzles", "Puzzles", "🧩"),
    ("Chess", "Chess", "♞"),
    ("Cricket", "Cricket", "🏏"),
    ("Health_Human_Body", "Health & Human Body", "❤️"),
    ("Olympics", "Olympics", "🥇"),
    ("Formula", "Formula", "🏎️"),
    ("IPL", "IPL", "📡"),
    ("Operating_Systems", "Operating Systems", "🖳"),
    ("Python", "Python", "🐍"),
    ("Java", "Java", "☕"),
    ("Algorithms_Data_Structures", "Algorithms & Data Structures", "🔀"),
    ("Computer_Basics", "Computer Basics", "🖥️"),
    ("Animals", "Animals", "🐾"),
    ("Birds", "Birds", "🐦"),
    ("Plants", "Plants", "🌱"),
    ("General_Trivia", "General Trivia", "❓"),
    ("Oceans_Marine_Life", "Oceans & Marine Life", "🌊"),
    ("Mountains_Rivers_India", "Mountains & Rivers (India Only)", "⛰️"),
    ("Travel_Tourism", "Travel & Tourism", "✈️"),
    ("Countries_Capitals", "Countries & Capitals", "🌍"),
    ("Board_Games", "Board Games", "🎲"),
    ("Number_Puzzles", "Number Puzzles", "🔢"),
    ("Languages", "Languages", "💬"),
    ("Famous_People", "Famous People", "🧑‍🎤"),
    ("Mobile_Apps", "Mobile & Apps", "📱"),
    ("Brain_Teasers", "Brain Teasers", "🧠"),
    ("Mental_Math", "Mental Math", "➗"),
    ("Cinema", "Cinema", "🎬"),
    ("Photography", "Photography", "📷"),
    ("UIUX_Design", "UI/UX Design", "🎨"),
    ("HTML", "HTML", "📄"),
    ("CSS", "CSS", "🎨"),
    ("Scientists", "Scientists", "🔬"),
    ("Law_Constitution", "Law & Constitution", "⚖️"),
    ("Indian_History", "Indian History", "🏯"),
    ("World_History", "World History", "🌎"),
    ("Environment", "Environment", "🌿"),
    ("Technology", "Technology", "🛠️"),
    ("Logical_Reasoning", "Logical Reasoning", "🧠"),
    ("Funny_Questions", "Funny Questions", "😂"),
    ("Crazy_Facts", "Crazy Facts", "🤯"),
    ("Trick_Questions", "Trick Questions", "🎭"),
]

# sanity: 56 categories
assert len(CATEGORIES) == 56
